import z from 'zod'

const envSchema = z.object({
  EXPO_PUBLIC_REVENUE_CAT_IOS_API_KEY: z.string().min(1),
  EXPO_PUBLIC_REVENUE_CAT_ANDROID_API_KEY: z.string().min(1),
  EXPO_PUBLIC_ENTITLEMENT_IDENTIFIER: z.string().min(1),
})

export const env = envSchema.parse({
  EXPO_PUBLIC_REVENUE_CAT_IOS_API_KEY: process.env.EXPO_PUBLIC_REVENUE_CAT_IOS_API_KEY,
  EXPO_PUBLIC_REVENUE_CAT_ANDROID_API_KEY: process.env.EXPO_PUBLIC_REVENUE_CAT_ANDROID_API_KEY,
  EXPO_PUBLIC_ENTITLEMENT_IDENTIFIER: process.env.EXPO_PUBLIC_ENTITLEMENT_IDENTIFIER,
})
